import type { Metadata } from "next";
import "./globals.css";
import { roboto } from "../utils/fonts";
import Footer from "../components/App/Footer";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="es">
			<body className={roboto.className}>{children}</body>
			<Footer />
		</html>
	);
}
