enum Mechanics {
  Reconfigure = "Reconfigure [cost] ([Cost]: Attach to target creature you control; or unattach from a creature. Reconfigure only as a sorcery. While attached this isn't a creature.)",
  Modified = "(Equipment, Auras you control, and counters are modifications.)",
  Transformed_Sagas = "As this Saga enters and after your draw step, add a lore counter. Transform after [III/IV].",
  Ninjutsu = "Ninjutsu [cost] (Return an unblocked attacker you control to hand: Put this card onto the battlefield from your hand tapped and attacking.)",
  Channel = "Channel — [cost], Discard this card: ...",
  Adventure = "Adventure is a spell type, a subtype seen on instants and sorceries attached to permanent cards, primarily appearing on creatures. It was introduced in Throne of Eldraine.",
  Adamant = "Adamant — If at least three [color] mana was spent to cast this spell, ... (colored spells)",
  Food_Token = "{2}, {T}, Sacrifice this artifact: You gain 3 life.",
  Mentor = "Mentor (Whenever this creature attacks, put a +1/+1 counter on target attacking creature with lesser power.)",
  Surveil = "Surveil N (Look at the top N cards of your library, then put any number of them into your graveyard and the rest on top of your library in any order.)",
  Amass = "Amass [subtype] N (Put N +1/+1 counters on an Army you control. It’s also a [subtype]. If you don’t control an Army, create a 0/0 black [subtype] Army creature token first.)",
  Jump_Start = "Jump-start (You may cast this card from your graveyard by discarding a card in addition to paying its other costs. Then exile this card.)",
  Outlast = "Outlast [cost] ([Cost], {T}: Put a +1/+1 counter on this creature. Activate only as a sorcery.)",
  Bolster = "Bolster N (Choose a creature you control with the least toughness or tied for the least toughness among creatures you control. Put N +1/+1 counters on that creature.)",
  Prowess = "Prowess (Whenever you cast a noncreature spell, this creature gets +1/+1 until end of turn.)",
  Rebound = "Rebound (If this spell was cast from your hand, instead of putting it into your graveyard as it resolves, exile it and, at the beginning of your next upkeep, you may cast this card from exile without paying its mana cost.)",
  Delve = "Delve (Each card you exile from your graveyard while casting this spell pays for {1}.)",
  Exploit = "Exploit (When this creature enters the battlefield, you may sacrifice a creature.)",
  Raid = "Raid — …, if you attacked this turn, …",
  Dash = "Dash [cost] (You may cast this spell for its dash cost. If you do, it gains haste, and it's returned from the battlefield to its owner's hand at the beginning of the next end step.)",
  Ferocious = "Ferocious — …, if you control a creature with power 4 or greater, …",
  Formidable = "Formidable — ..., if creatures you control have total power 8 or greater, ...",
  Domain = "Domain — ... for each basic land type among lands you control.",
  Enlist = "Enlist (As this creature attacks, you may tap a nonattacking creature you control without summoning sickness. When you do, add its power to this creature's until end of turn.)",
  Sagas_Read_Ahead = "Read ahead (Choose a chapter and start with that many lore counters. Add one after your draw step. Skipped chapters don't trigger. Sacrifice after III.)",
  Stun_Counters = "If a permanent with a stun counter would become untapped, remove one from it instead.",
  Sagas = "As this Saga enters and after your draw step, add a lore counter. Sacrifice after [III/IV].",
  Historic_Spells = "Artifacts, legendaries, and Sagas are historic.",
  Kicker = "Kicker [cost] (You may pay an additional [cost] as you cast this spell.)",
  Legendary_Spells = "Legendary permanent or card. A player may not control two or more legendary permanents with the same name.",
  Hexproof_From = "Hexproof from [quality] (This permanent can't be the target of [quality] spells your opponents control or abilities of [quality] sources your opponents control.)",
  Delirium = "Delirium — If there are four or more card types among cards in your graveyard, …",
  Madness = "Madness [cost] (If you discard this card, discard it into exile. When you do, cast it for its madness cost or put it into your graveyard.)",
  Double_Faced = "Double-faced is a referable property for a card: Overgrown Pest and Invasion of Pyrulea look for double-faced cards while in the library. Multiple cards in March of the Machine also refer to being transformed, making it a quasi-typal synergy.",
  Flashback = "Flashback [cost] (You may cast this card from your graveyard for its flashback cost. Then exile it.)",
  Escalate = "Escalate [cost] (Pay this cost for each mode chosen beyond the first.)",
  Vehicles = "Vehicle cards have a special bronze and grey blocked card frame[10] and a power/toughness printed in a bronze-colored box. However, vehicles don't have power or toughness unless they become creatures.	",
  Historic = "Artifacts, legendaries, and Sagas are historic.",
  Pirates = "Creature Subtype (Pirates)",
  Tokens = "A token is a permanent that is not represented by a regular card with a casting cost. They are created by the effects of many different spells and abilities, rather than being cast from a zone (such as the hand) like normal cards.",
  Reanimator = "Is an archetype that consist of returning big creatures to the battlefield from the graveyard. Or strong permanents",
  Dwarf = "Creature SubType (Dwarf)",
  Foretell = "Foretell [cost] (During your turn, you may pay {2} and exile this card from your hand face down. Cast it on a later turn for its foretell cost.)ell",
  Snow_Permanents = "Snow is a supertype with no inherent functionality. Instead, it serves as an identifying characteristic of permanents and spells, and is closely tied to snow activation costs and mana costs. Snow is a replacement for the supertype 'Snow-Covered'.",
  Tribal = "Consists of an archetype of the same subtype pf creatures (Tribal)",
  Changeling = "Changeling (This card is every creature type.)",
  Annihilator = "Annihilator N (Whenever this creature attacks, defending player sacrifices N permanents.)",
  Level_Up = "Level up [cost] ([Cost]: Put a level counter on this. Level up only as a sorcery.)",
  Totem_Armor = "Umbra armor (If enchanted permanent would be destroyed, instead remove all damage marked on it and destroy this Aura.)",
  Artifacts = "Artifacts are permanents that represent magical items, animated constructs, pieces of equipment, or other objects and devices.[1] Artifact, the card type, is broader than the normal definition.",
  Energy_Counters = "Energy is a resource and mechanic.",
  Fabricate = "Fabricate N (When this permanent enters the battlefield, you may put N +1/+1 counters on it. If you don't, create N 1/1 colorless Servo artifact creature tokens.)",
  Improvise = "Improvise (Your artifacts can help cast this spell. Each artifact you tap after you're done activating mana abilities pays for {1}.)",
  Revolt = "Revolt — ..., if a permanent you controlled left the battlefield this turn, ...",
  Threshold = "Threshold — As long as there are seven or more cards in your graveyard, …",
  Metalcraft = "Metalcraft — ..., as long as you control three or more artifacts, ...",
  Enchantments = "Enchantment is a card type that represents persistent magical effects, usually remaining in play indefinitely.",
  Landfall = "Landfall — Whenever a land enters the battlefield under your control, … (nonland permanents). Landfall — If you had a land enter the battlefield under your control this turn, … (instants and sorceries)",
  Party = "(Your party consists of up to one each of Cleric, Rogue, Warrior, and Wizard.)",
  Connive = "Connive (Draw a card, then discard a card. If you discarded a nonland card, put a +1/+1 counter on this creature.)",
  Alliance = "Alliance — Whenever another creature enters the battlefield under your control, … (creatures)",
  Shield_Counter = "Shield counters provide two benefits. First, if a permanent with a shield counter on it would be destroyed by an effect, a shield counter is removed from the permanent instead of it being destroyed.",
  Casualty = "Casualty N (As you cast this spell, you may sacrifice a creature with power N or greater. When you do, copy this spell.)",
  Blitz = "Blitz [cost] (If you cast this spell for its blitz cost, it gains haste and 'When this creature dies, draw a card'. Sacrifice it at the beginning of the next end step.)",
  Treasure = "{T}, Sacrifice this artifact: Add one mana of any color.",
  Venture_into_the_Dungeon = "Venture into the dungeon (Enter the first room or advance to the next room) Venture into [quality] (If you’re in a dungeon, advance to the next room.If you’re not, enter[quality].Enter the first room or advance to the next room) ",
  Roll_a_dice = "Roll a X Dice: (Roll a dice and see the result to and the effect in the card of the result)",
  Enchantment_Class = "Each Class has three abilities in sections of its text box, called Class abilities. The abilities are arranged vertically like Sagas and have vertical artwork of the D&D symbol of the creature class in its art.",
  Equipment = "Equipment is an artifact subtype that has the 'equip' keyword ability. By paying the equip cost (which can only be done at sorcery speed), it attaches to a creature you control. If that creature leaves play, the Equipment becomes unattached and remains in play. Paying the equip cost also allows the Equipment to be moved from one creature to another.",
  Pack_tactics = "Pack tactics — Whenever CARDNAME attacks, if you attacked with creatures with total power 6 or greater this combat, ...",
  Choose_one = "When a Choose one card is played select one of the options, and for the rest of the game that option is selected until the card is removed.",
}

interface MechanicsIndex {
  [key: string]: string;
}

const mechanicText: MechanicsIndex = {
  Reconfigure: Mechanics.Reconfigure,
  Modified: Mechanics.Modified,
  Transformed_Sagas: Mechanics.Transformed_Sagas,
  Ninjutsu: Mechanics.Ninjutsu,
  Channel: Mechanics.Channel,
  Adventure: Mechanics.Adventure,
  Adamant: Mechanics.Adamant,
  Food_Token: Mechanics.Food_Token,
  Mentor: Mechanics.Mentor,
  Surveil: Mechanics.Surveil,
  Amass: Mechanics.Amass,
  Jump_Start: Mechanics.Jump_Start,
  Outlast: Mechanics.Outlast,
  Bolster: Mechanics.Bolster,
  Prowess: Mechanics.Prowess,
  Rebound: Mechanics.Rebound,
  Delve: Mechanics.Delve,
  Exploit: Mechanics.Exploit,
  Raid: Mechanics.Raid,
  Dash: Mechanics.Dash,
  Ferocious: Mechanics.Ferocious,
  Formidable: Mechanics.Formidable,
  Domain: Mechanics.Domain,
  Enlist: Mechanics.Enlist,
  Sagas_Read_Ahead: Mechanics.Sagas_Read_Ahead,
  Stun_Counters: Mechanics.Stun_Counters,
  Sagas: Mechanics.Sagas,
  Historic_Spells: Mechanics.Historic_Spells,
  Kicker: Mechanics.Kicker,
  Legendary_Spells: Mechanics.Legendary_Spells,
  Hexproof_From: Mechanics.Hexproof_From,
  Delirium: Mechanics.Delirium,
  Madness: Mechanics.Madness,
  Double_Faced: Mechanics.Double_Faced,
  Flashback: Mechanics.Flashback,
  Escalate: Mechanics.Escalate,
  Vehicles: Mechanics.Vehicles,
  Historic: Mechanics.Historic,
  Pirates: Mechanics.Pirates,
  Tokens: Mechanics.Tokens,
  Reanimator: Mechanics.Reanimator,
  Dwarf: Mechanics.Dwarf,
  Foretell: Mechanics.Foretell,
  Snow_Permanents: Mechanics.Snow_Permanents,
  Tribal: Mechanics.Tribal,
  Changeling: Mechanics.Changeling,
  Annihilator: Mechanics.Annihilator,
  Level_Up: Mechanics.Level_Up,
  Totem_Armor: Mechanics.Totem_Armor,
  Artifacts: Mechanics.Artifacts,
  Energy_Counters: Mechanics.Energy_Counters,
  Fabricate: Mechanics.Fabricate,
  Improvise: Mechanics.Improvise,
  Revolt: Mechanics.Revolt,
  Threshold: Mechanics.Threshold,
  Metalcraft: Mechanics.Metalcraft,
  Enchantments: Mechanics.Enchantments,
  Landfall: Mechanics.Landfall,
  Party: Mechanics.Party,
  Connive: Mechanics.Connive,
  Alliance: Mechanics.Alliance,
  Shield_Counter: Mechanics.Shield_Counter,
  Casualty: Mechanics.Casualty,
  Blitz: Mechanics.Blitz,
  Treasure: Mechanics.Treasure,
  Venture_into_the_Dungeon: Mechanics.Venture_into_the_Dungeon,
  Roll_a_dice: Mechanics.Roll_a_dice,
  Enchantment_Class: Mechanics.Enchantment_Class,
  Equipment: Mechanics.Equipment,
  Pack_tactics: Mechanics.Pack_tactics,
  Choose_one: Mechanics.Choose_one,
};

export { mechanicText };
